export interface Userinfo {
    name : string,
    age : number,
    gender : string,
    weight : number,
    height : number,
    waist : number,
    hip : number,
    result : number,
    timestamp : Date,
    bmiaccuracy : Number,
    whraccuracy : Number,
    convenient : Number,
    rating : Number,
    comment : string,
};