import type { Metadata } from 'next'
import { Inter ,Prompt } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const prompt = Prompt({ 
  subsets: ['latin','thai'],
  weight: ['100','200','300','400','500','600','700','800','900']
})

export const metadata: Metadata = {
  title: 'Body Dough',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={`${prompt.className} bg-orange-300`}>
        {children}
      </body>
    </html>
  )
}
